name: Test add.py
on:
  push:
    paths:
      - add.py
      - unit_test_add.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: run unit test
      run: |
        python3 -m unittest unit_test_add.py
